# Generated by Django 5.0.3 on 2024-03-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="fullname",
        ),
    ]
