# Generated by Django 5.0.3 on 2024-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_name_order_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default="1"),
            preserve_default=False,
        ),
    ]
